version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:java21-graalvm
    environment:
      EULA: "true"
      VERSION: 1.20.2
      TYPE: FABRIC
      USE_AIKAR_FLAGS: TRUE
      MEMORY: "10G"
      MODRINTH_PROJECTS: alternate-current,async-locator,c2me-fabric,carpet,cloth-config,fabric-api,fabric-language-kotlin,fallingtree,ferrite-core,ebe,krypton,ksyxis,lazydfu,leashable-villagers,lithium,modernfix,servercore,slumber,spark,starlight,threadtweak,vmp-fabric:alpha
      # missing: clumps
      MODRINTH_ALLOWED_VERSION_TYPE: "release"
    volumes:
    - ./data:/data